MOD_NAME: testmod
MOD_DISPLAY_NAME: testing_worldgen
MOD_OUTPUTS:
  CK3: "C:\\Users\\vaniv\\Documents\\Paradox Interactive\\Crusader Kings III\\mod"
  # V3: "C:\\Users\\vaniv\\Documents\\Paradox Interactive\\Victoria 3\\mod"
  # HOI4: "C:\\Users\\vaniv\\Documents\\Paradox Interactive\\Hearts of Iron IV\\mod"
BASE_CK3_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Crusader Kings III\\game"
BASE_EU4_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Europa Universalis IV\\game"
BASE_V3_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Victoria 3\\game"
BASE_HOI4_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Hearts of Iron IV"
CONTINENT_LISTS:
- - e-e_islam
  - 61-k_egypt
  - 61-k_yemen
  - 61-k_syria
  - 22-d_mecca
  - 24-d_bahrain
  - 24-d_tahert
  - 24-d_basra
- - e-e_latin
  - 61-k_scotland
  - 61-k_france
  - 61-k_lancaster
  - 61-k_aquitaine
  - 22-d_latium
  - 22-d_barcelona
  - 24-d_asturias
  - 24-d_brittany
  - 24-d_flanders
  - 24-d_munster
  - 24-d_valencia
- - e-e_baltic
  - 61-k_bavaria
  - 61-k_pomerania
  - 61-k_saxony
  # - 61-k_hungary
  - 22-d_bohemia
  # - 22-d_osterreich
  # - 24-d_east_franconia
  # - 24-d_west_franconia
  - 24-d_lower_silesia
  - 24-d_moravia
  - 24-d_tyrol
ISLAND_LIST:
# - 22-d_latium
# - 6-k_cyprus
- 6-k_krete
# - 9-d_iceland
# - 4-d_gotland
# - 3-d_northern_isles
# - 5-d_canarias
seed: 20240512
n_x: 171
n_y: 57
box_width: 8
box_height: 16
max_x: 8192
max_y: 4096
ck3n_x: 338
ck3n_y: 129
RELIGION_DIR: "data"
PLAYER_HOLY_SITES: False
GUARANTEED_INNOS:
- tribal
- innovation_chronicle_writing
- innovation_hereditary_rule
RANDOM_INNOS:
  early_medieval: 3
BANNED_INNOS:
- innovation_baliffs
BORDER_SIZE_LIST:
- 4
- 4
- 4
- 4
- 4
- 4
BORDER_TERRAIN_TEMPLATE:
  farmlands: 0
  hills: 6
  mountains: 6
  plains: 6
  rough: 6
CENTER_SIZE_LIST:
- 7
- 5
- 5
- 5
CENTER_TERRAIN_TEMPLATE:
  farmlands: 0
  hills: 4
  mountains: 2
  plains: 8
  rough: 4
  fixed:
    0: farmlands
    7: farmlands
    12: farmlands
    17: farmlands
KINGDOM_SIZE_LIST:
- - 6
  - 4
  - 4
  - 4
  - 4
- - 4
  - 4
  - 3
  - 3
- - 4
  - 4
  - 3
  - 3
- - 4
  - 4
  - 3
KINGDOM_TERRAIN_TEMPLATE:
  farmlands: 0
  hills: 16
  mountains: 8
  plains: 20
  rough: 16
  fixed:
    0: farmlands
ISLAND_TERRAIN_TEMPLATE:
  hills: 10
  mountains: 10
  plains: 10