MOD_NAME: testmod
MOD_DISPLAY_NAME: testing_worldgen
MOD_OUTPUTS:
  # CK3: "C:\\Users\\vaniv\\Documents\\Paradox Interactive\\Crusader Kings III\\mod"
  V3: "C:\\Users\\vaniv\\Documents\\Paradox Interactive\\Victoria 3\\mod"
  HOI4: "C:\\Users\\vaniv\\Documents\\Paradox Interactive\\Hearts of Iron IV\\mod"
BASE_CK3_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Crusader Kings III\\game"
BASE_EU4_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Europa Universalis IV\\game"
BASE_V3_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Victoria 3\\game"
BASE_HOI4_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Hearts of Iron IV"
CONTINENT_LISTS:
- - e_islam
  - 61-k_egypt
  - 61-k_yemen
  - 61-k_syria
  - 22-d_mecca
  - 24-d_bahrain
  - 24-d_najd
  - 24-d_shammar
- - e_europe
  - 61-k_east_francia
  - 61-k_france
  - 61-k_bavaria
  - 61-k_aquitaine
  - 22-d_latium
  - 22-d_lombardia
  - 24-d_alsace
  - 24-d_toscana
  - 24-d_genoa
  - 24-d_capua
  - 24-d_west_franconia
- - e_eeurope
  - 61-k_norway
  - 61-k_burgundy
  - 61-k_hungary
  - 22-d_kiev
  - 24-d_silesia
  - 24-d_bohemia
  - 24-d_amdo
n_x: 171
n_y: 57
max_x: 5632
max_y: 2048
RELIGION_DIR: "data"
GUARANTEED_INNOS:
- tribal
- innovation_chronicle_writing
RANDOM_INNOS:
  early_medieval: 3
BANNED_INNOS:
- innovation_hereditary_rule
- innovation_baliffs
BORDER_SIZE_LIST:
- 4
- 4
- 4
- 4
- 4
- 4
BORDER_TERRAIN_TEMPLATE:
  farmlands: 0
  hills: 6
  mountains: 6
  plains: 6
  rough: 6
CENTER_SIZE_LIST:
- 7
- 5
- 5
- 5
CENTER_TERRAIN_TEMPLATE:
  farmlands: 4
  hills: 4
  mountains: 2
  plains: 8
  rough: 4
KINGDOM_SIZE_LIST:
- - 6
  - 4
  - 4
  - 4
  - 4
- - 4
  - 4
  - 3
  - 3
- - 4
  - 4
  - 3
  - 3
- - 4
  - 4
  - 3
KINGDOM_TERRAIN_TEMPLATE:
  farmlands: 1
  hills: 16
  mountains: 8
  plains: 20
  rough: 16