MOD_NAME: testmod
MOD_DISPLAY_NAME: testing_worldgen
MOD_OUTPUTS:
  CK3: "C:\\Users\\vaniv\\Documents\\Paradox Interactive\\Crusader Kings III\\mod"
  V3: "C:\\Users\\vaniv\\Documents\\Paradox Interactive\\Victoria 3\\mod"
BASE_CK3_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Crusader Kings III\\game"
BASE_EU4_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Europa Universalis IV\\game"
BASE_V3_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Victoria 3\\game"
BASE_HOI4_DIR: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Hearts of Iron IV\\game"
CONTINENT_LISTS:
- - e_islam
  - k_egypt
  - k_yemen
  - k_syria
  - c_mecca
  - b_bahrain
  - b_najd
  - b_shammar
- - e_europe
  - k_east_francia
  - k_france
  - k_bavaria
  - c_latium
  - b_alsace
  - b_toscana
  - b_genoa
- - e_eeurope
  - k_norway
  - k_burgundy
  - k_hungary
  - c_kiev
  - b_silesia
  - b_bohemia
  - b_amdo
RELIGION_DIR: "data"
GUARANTEED_INNOS:
- tribal
- innovation_chronicle_writing
RANDOM_INNOS:
  early_medieval: 3
BANNED_INNOS:
- innovation_hereditary_rule
- innovation_baliffs
BORDER_SIZE_LIST:
- 4
- 4
- 4
- 4
- 4
- 4
BORDER_TERRAIN_TEMPLATE:
  farmlands: 0
  hills: 6
  mountains: 6
  plains: 6
  rough: 6
CENTER_SIZE_LIST:
- 7
- 5
- 5
- 5
CENTER_TERRAIN_TEMPLATE:
  farmlands: 4
  hills: 4
  mountains: 2
  plains: 8
  rough: 4
KINGDOM_SIZE_LIST:
- - 6
  - 4
  - 4
  - 4
  - 4
- - 4
  - 4
  - 3
  - 3
- - 4
  - 4
  - 3
  - 3
- - 4
  - 4
  - 3
KINGDOM_TERRAIN_TEMPLATE:
  farmlands: 1
  hills: 16
  mountains: 8
  plains: 20
  rough: 16